# Generated by Django 2.2.4 on 2019-08-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='audio',
            field=models.FilePathField(default='/Users/marcogdepinto/PycharmProjects/DjangoRestDeepLearning/media', path='/Users/marcogdepinto/PycharmProjects/DjangoRestDeepLearning/media'),
        ),
    ]
