# Generated by Django 2.2.4 on 2019-08-24 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_filemodel_audio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filemodel',
            old_name='audio',
            new_name='path',
        ),
    ]
