# Generated by Django 2.2.4 on 2019-08-16 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20190815_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
