# Generated by Django 2.2.4 on 2019-09-04 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_filesubmissionsmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileSubmissionsModel',
        ),
    ]
