# Generated by Django 2.2.4 on 2019-10-06 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_delete_filesubmissionsmodel'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='filemodel',
            unique_together={('file', 'path')},
        ),
    ]
