# Generated by Django 2.2.4 on 2019-08-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20190818_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
